---
# tasks file for default_packages

- name: Установка программ #Имя задачи 
  apt: #Используемый модуль
    name: "{{ item }}" #Имя пакета из цикла
    state: present #Параметр действия. present - установить, absent - удалить
  loop:
    - "{{ packages_to_install }}" #Цикл будет перебирать все значения из переменной "packages"
  when: ansible_distribution == "Debian" # Выполнится только на Debian системах

- name: Configuring zabbix-agent
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  when: ansible_distribution == "Debian"  
- name: Restarting and enabling zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  when: ansible_distribution == "Debian"

- name: Меняем имя машины
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when:
    - inventory_hostname != ansible_hostname
    - ansible_distribution == "Debian"
