--- 
# vars file for default_packages
packages_to_install:
  - dnsutils
  - net-tools
  - zabbix-agent
  - rsync
  - rsyslog
  - mc
  - curl
  - wget
  - apt-transport-https
  - gnupg2
  - software-properties-common
  - ca-certificates
  - parted
  - openssh-server
zbx_server_addr: 127.0.0.1
