---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        ubuntu-24: #Имя машины
          ansible_host: 84.252.129.186 #Адрес машины
        debian-11-1: #Имя машины
          ansible_host: 130.193.37.253 #Адрес машины
        debian-11-2: #Имя машины
          ansible_host: 89.169.139.126 #Адрес машины
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "usert3"
    ansible_ssh_private_key_file: "~/.ssh/yc" # Указываем путь к приватному ключу
    connection_protocol: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения
