---
# tasks file for nginx_custom

- name: Установка Nginx
  apt:
    name: "nginx"
    state: present

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'debian-11-2' in inventory_hostname" # Выполнится только тогда, когда в имени есть debian-11-2
  notify: "Nginx Reloader"

- name: Настройка прокси на debian-11-1
  ansible.builtin.template:
    src: proxy.conf.j2
    dest: /etc/nginx/sites-available/default
  when: "'debian-11-1' in inventory_hostname"
  notify: "Nginx Reloader"
